input_path: factr_teleop/raw_data/0728
output_path: processed_data/0728

cameras_topics:
  - /camera_0/rgb/image_raw
  - /camera_1/rgb/image_raw

obs_topics:
  - /joint_external_torque
  - /gripper/state

action_config:
  /joint_states: 7
  /gripper/state: 1
