input_path: factr_teleop/raw_data/0728
output_path: processed_data/0728

cameras_topics:
  - /camera_0/rgb/image_raw
  - /camera_1/rgb/image_raw

obs_topics:
  - /joint_states
  - /joint_external_torque
  # - /gripper/state
  # - /robot/end_effector_pose

# 暂时注释掉，等你有 cmd topic 再启用
# action_config:
#   /franka/cmd_joint_positions: 7
#   /gripper/cmd_position: 1
